
// =================================================================================================

// the code below works well, though errors are underlined
@@include('./chunks/_hi.js')
@@include('./chunks/_card_slider.js')
@@include('./chunks/_filter.js')
@@include('./chunks/_accordion.js')
@@include('./chunks/_tabs.js')
@@include('./chunks/_form.js')
@@include('./chunks/_counter.js')
@@include('./chunks/_burger.js')
@@include('./chunks/_popup.js')
@@include('./chunks/_vertical_tabs.js')
@@include('./chunks/_columns_number.js')
@@include('./chunks/_single_custom_select.js')
@@include('./chunks/_swiper_slider.js')
@@include('./chunks/_colour_select.js')
@@include('./chunks/_size_select.js')
@@include('./chunks/_custom_select.js')
@@include('./chunks/_tabs_page.js')
@@include('./chunks/_advert_top.js')
@@include('./chunks/_fixed_header.js')
@@include('./chunks/_up_to.js')
@@include('./chunks/_show_more.js')
@@include('./chunks/_aside.js')